"""Provisional plan generation — a static curriculum lookup.

**This is not a scheduler.** It does not consult readiness, does not evaluate
prerequisites, does not apply mix ratios, and does not optimise anything. It maps
a self-assessed level to a fixed ordered list of patterns, takes the lowest-rated
active problems for each, and packs them into days until the stated daily budget is
reached (spec §9, §21 deliverable 5).

The real block assembler arrives in Phase 1 and replaces this entirely. Until then
the plan is labelled `provisional` everywhere it is shown.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from dsa_coach.models import (
    ItemRole,
    ItemType,
    Level,
    Pattern,
    Plan,
    PlanItem,
    PlanStatus,
    Problem,
    ProblemPattern,
    User,
    UserGoal,
)
from dsa_coach.tuning import (
    CURRICULUM_BY_LEVEL,
    PROVISIONAL_BUDGET_FILL,
    PROVISIONAL_MINUTES_BY_DIFFICULTY,
    PROVISIONAL_MINUTES_DEFAULT,
    PROVISIONAL_PLAN_DAYS,
    PROVISIONAL_PROBLEMS_PER_PATTERN,
)


@dataclass(frozen=True)
class _Candidate:
    problem_id: uuid.UUID
    minutes: int
    pattern_slug: str


async def select_curriculum_problems(session: AsyncSession, level: Level) -> list[_Candidate]:
    """Deterministic lookup: for each pattern in the level's curriculum, the
    lowest-rated active problems, ordered by (rating, slug) so ties are stable."""
    candidates: list[_Candidate] = []
    seen: set[uuid.UUID] = set()

    for slug in CURRICULUM_BY_LEVEL[level]:
        rows = (
            (
                await session.execute(
                    select(Problem)
                    .join(ProblemPattern, ProblemPattern.problem_id == Problem.id)
                    .join(Pattern, Pattern.id == ProblemPattern.pattern_id)
                    .where(Pattern.slug == slug, Problem.is_active.is_(True))
                    .order_by(Problem.rating.asc(), Problem.slug.asc())
                    .limit(PROVISIONAL_PROBLEMS_PER_PATTERN)
                )
            )
            .scalars()
            .all()
        )

        for problem in rows:
            if problem.id in seen:
                continue
            seen.add(problem.id)
            candidates.append(
                _Candidate(
                    problem_id=problem.id,
                    minutes=PROVISIONAL_MINUTES_BY_DIFFICULTY[problem.difficulty]
                    if problem.difficulty is not None
                    else PROVISIONAL_MINUTES_DEFAULT,
                    pattern_slug=slug,
                )
            )

    return candidates


async def build_provisional_plan(session: AsyncSession, user: User, goal: UserGoal) -> Plan:
    """Create plan version 1 for a freshly onboarded user."""
    candidates = await select_curriculum_problems(session, goal.self_assessed_level)

    daily_budget = int(goal.minutes_per_day * PROVISIONAL_BUDGET_FILL)
    days = min(PROVISIONAL_PLAN_DAYS, goal.days_per_week)

    plan = Plan(
        user_id=user.id,
        goal_id=goal.id,
        version=1,
        status=PlanStatus.PROVISIONAL,
        summary=(
            f"Provisional starting plan for a {goal.self_assessed_level.value} learner. "
            "Generated by static curriculum lookup — not yet based on any evidence "
            "about your actual level."
        ),
        generation_context={
            "generator": "static_curriculum_lookup",
            "generator_version": "phase0",
            "level": goal.self_assessed_level.value,
            "curriculum": CURRICULUM_BY_LEVEL[goal.self_assessed_level],
            "daily_budget_minutes": daily_budget,
            "days": days,
            "note": (
                "No readiness model, prerequisite evaluation, or mix ratios were used. "
                "Replaced once placement produces evidence."
            ),
        },
    )
    session.add(plan)
    await session.flush()

    sequence = 0
    index = 0
    for _day in range(days):
        block_id = uuid.uuid4()
        remaining = daily_budget
        placed_in_block = 0

        while index < len(candidates):
            candidate = candidates[index]
            # Always place at least one item per day, so a tight budget still
            # produces a usable plan rather than an empty one.
            if candidate.minutes > remaining and placed_in_block > 0:
                break
            session.add(
                PlanItem(
                    plan_id=plan.id,
                    block_id=block_id,
                    sequence=sequence,
                    problem_id=candidate.problem_id,
                    item_type=ItemType.PRACTICE,
                    role=ItemRole.WEAKNESS,
                    target_minutes=candidate.minutes,
                )
            )
            remaining -= candidate.minutes
            sequence += 1
            placed_in_block += 1
            index += 1

        if index >= len(candidates):
            break

    await session.flush()
    return plan
