"""trigger relevance and readiness snapshot

Revision ID: 0a86b3861339
Revises: 13aa9555adef
Create Date: 2026-09-06 20:50:00.786605
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0a86b3861339"
down_revision: str | None = "13aa9555adef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # A NOT NULL column added to a table that already has rows needs a
    # server_default to backfill them. Autogenerate does not add one, and the
    # omission only shows up against a populated database — never a fresh one.
    #
    # Existing attempts are backfilled as not counting toward the trigger:
    # relevance depends on facts (whether a re-solve lapsed, whether an earlier
    # attempt already counted that sitting) that cannot be reconstructed after
    # the fact, and inventing them would be fabricating evidence.
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "counts_toward_trigger",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table("trigger_batches", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "readiness_snapshot",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'{}'"),
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trigger_batches", schema=None) as batch_op:
        batch_op.drop_column("readiness_snapshot")

    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_column("counts_toward_trigger")

    # ### end Alembic commands ###
