"""device pairing and revocable tokens

Revision ID: 0ebe455a34f6
Revises: 0a86b3861339
Create Date: 2026-09-07 01:55:33.901208
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import dsa_coach.db


revision: str = "0ebe455a34f6"
down_revision: str | None = "0a86b3861339"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("extension", "web", name="device_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_devices_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "pairing_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("failed_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pairing_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pairing_codes_code_hash"), ["code_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_pairing_codes_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pairing_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pairing_codes_user_id"))
        batch_op.drop_index(batch_op.f("ix_pairing_codes_code_hash"))

    op.drop_table("pairing_codes")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_user_id"))
        batch_op.drop_index(batch_op.f("ix_devices_token_hash"))

    op.drop_table("devices")
    # ### end Alembic commands ###
