"""phase 1 readiness retention triggers

Revision ID: 13aa9555adef
Revises: 855d289b60c2
Create Date: 2026-09-06 20:44:00.437382
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "13aa9555adef"
down_revision: str | None = "855d289b60c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pattern_baseline_buckets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("pattern_id", sa.Uuid(), nullable=False),
        sa.Column("bucket", sa.Integer(), nullable=False),
        sa.Column("alpha", sa.Float(), nullable=False),
        sa.Column("beta", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scoring_config_version",
            sa.Enum("v1", name="scoring_config_version", native_enum=False),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("alpha > 0 AND beta > 0", name="ck_baseline_positive"),
        sa.ForeignKeyConstraint(["pattern_id"], ["patterns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "pattern_id", "bucket", name="uq_baseline_bucket"),
    )
    with op.batch_alter_table("pattern_baseline_buckets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pattern_baseline_buckets_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "pattern_ratings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("pattern_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("rd", sa.Float(), nullable=False),
        sa.Column("volatility", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scoring_config_version",
            sa.Enum("v1", name="scoring_config_version", native_enum=False),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pattern_id"], ["patterns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "pattern_id", name="uq_pattern_rating"),
    )
    with op.batch_alter_table("pattern_ratings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pattern_ratings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "trigger_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_ids", sa.JSON(), nullable=False),
        sa.Column("relevant_count", sa.Integer(), nullable=False),
        sa.Column("material", sa.Boolean(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "no_change",
                "prescribed",
                "pending_agent",
                name="trigger_outcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trigger_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trigger_batches_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_trigger_batches_user_time", ["user_id", "evaluated_at"], unique=False
        )

    op.create_table(
        "review_schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("fsrs_state", sa.Integer(), nullable=False),
        sa.Column("fsrs_step", sa.Integer(), nullable=True),
        sa.Column("fsrs_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "problem_id", name="uq_review_schedule"),
    )
    with op.batch_alter_table("review_schedule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_schedule_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_schedule_user_id"), ["user_id"], unique=False)

    op.create_table(
        "readiness_predictions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("predicted_score", sa.Float(), nullable=False),
        sa.Column("uncertainty", sa.Float(), nullable=False),
        sa.Column("actual_outcome", sa.Float(), nullable=True),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("readiness_predictions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_readiness_predictions_model",
            ["user_id", "model_version", "resolved_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_readiness_predictions_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("readiness_predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_readiness_predictions_user_id"))
        batch_op.drop_index("ix_readiness_predictions_model")

    op.drop_table("readiness_predictions")
    with op.batch_alter_table("review_schedule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_schedule_user_id"))
        batch_op.drop_index(batch_op.f("ix_review_schedule_due_at"))

    op.drop_table("review_schedule")
    with op.batch_alter_table("trigger_batches", schema=None) as batch_op:
        batch_op.drop_index("ix_trigger_batches_user_time")
        batch_op.drop_index(batch_op.f("ix_trigger_batches_user_id"))

    op.drop_table("trigger_batches")
    with op.batch_alter_table("pattern_ratings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pattern_ratings_user_id"))

    op.drop_table("pattern_ratings")
    with op.batch_alter_table("pattern_baseline_buckets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pattern_baseline_buckets_user_id"))

    op.drop_table("pattern_baseline_buckets")
    # ### end Alembic commands ###
