"""phase 5 teaching and consent

Revision ID: 7880eee4ef74
Revises: ad9da7c2d3c9
Create Date: 2026-09-07 03:14:10.992765
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types render as `dsa_coach.db.X`; autogenerate does not add
# this import itself, and without it the migration fails at import time.
import dsa_coach.db


revision: str = "7880eee4ef74"
down_revision: str | None = "ad9da7c2d3c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("monitoring", "code_capture", name="consent_scope", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.Enum("once", "always", "never", name="consent_decision", native_enum=False),
            nullable=False,
        ),
        sa.Column("consent_version", sa.String(length=32), nullable=False),
        sa.Column("disclosure_text_hash", sa.String(length=64), nullable=False),
        sa.Column("granted_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "attempt_code",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("retention_until", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attempt_code", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attempt_code_attempt_id"), ["attempt_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_attempt_code_retention_until"), ["retention_until"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_attempt_code_user_id"), ["user_id"], unique=False)

    op.create_table(
        "teaching_exchanges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("hint", "diagnosis", "review", "mock", name="teaching_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("hint_level", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("degraded", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teaching_exchanges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_teaching_exchanges_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ix_teaching_user_time", ["user_id", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teaching_exchanges", schema=None) as batch_op:
        batch_op.drop_index("ix_teaching_user_time")
        batch_op.drop_index(batch_op.f("ix_teaching_exchanges_user_id"))

    op.drop_table("teaching_exchanges")
    with op.batch_alter_table("attempt_code", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempt_code_user_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_code_retention_until"))
        batch_op.drop_index(batch_op.f("ix_attempt_code_attempt_id"))

    op.drop_table("attempt_code")
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consents_user_id"))

    op.drop_table("consents")
    # ### end Alembic commands ###
