"""initial phase 0 schema

Revision ID: 855d289b60c2
Revises:
Create Date: 2026-09-06 20:15:22.814858
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "855d289b60c2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogue_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("license", sa.String(length=200), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=True),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("transformation_notes", sa.Text(), nullable=False),
        sa.Column("known_limitations", sa.Text(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "patterns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("foundational", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("preferred_language", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pattern_prerequisites",
        sa.Column("pattern_id", sa.Uuid(), nullable=False),
        sa.Column("requires_pattern_id", sa.Uuid(), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.CheckConstraint("pattern_id != requires_pattern_id", name="ck_prereq_not_self"),
        sa.CheckConstraint("strength > 0 AND strength <= 1", name="ck_prereq_strength"),
        sa.ForeignKeyConstraint(["pattern_id"], ["patterns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requires_pattern_id"], ["patterns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pattern_id", "requires_pattern_id"),
    )
    op.create_table(
        "problems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("rating_rd", sa.Integer(), nullable=False),
        sa.Column(
            "rating_source",
            sa.Enum("manual", "contest_derived", name="rating_source", native_enum=False),
            nullable=False,
        ),
        sa.Column("catalogue_source_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rating BETWEEN 800 AND 3500", name="ck_problem_rating_range"),
        sa.CheckConstraint("rating_rd BETWEEN 0 AND 500", name="ck_problem_rating_rd_range"),
        sa.ForeignKeyConstraint(
            ["catalogue_source_id"], ["catalogue_sources.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_problem_provider_external_id"),
        sa.UniqueConstraint("provider", "slug", name="uq_problem_provider_slug"),
    )
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.create_index("ix_problems_active_rating", ["is_active", "rating"], unique=False)

    op.create_table(
        "user_goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("target_companies", sa.JSON(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("days_per_week", sa.Integer(), nullable=False),
        sa.Column("minutes_per_day", sa.Integer(), nullable=False),
        sa.Column(
            "self_assessed_level",
            sa.Enum("beginner", "intermediate", "advanced", name="level", native_enum=False),
            nullable=False,
        ),
        sa.Column("approx_problems_solved", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("days_per_week BETWEEN 1 AND 7", name="ck_goal_days_per_week"),
        sa.CheckConstraint("minutes_per_day BETWEEN 10 AND 600", name="ck_goal_minutes"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_goals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_goals_user_id"), ["user_id"], unique=False)

    op.create_table(
        "attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resolution",
            sa.Enum(
                "independent",
                "after_hint",
                "after_editorial",
                "failed",
                "unknown",
                name="resolution",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "blocker",
            sa.Enum(
                "pattern_not_recognized",
                "pattern_known_impl_failed",
                "edge_cases",
                "complexity",
                "data_structure_choice",
                "language_api",
                "misread_problem",
                name="blocker",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("confidence_cold_redo", sa.Integer(), nullable=True),
        sa.Column("hint_level_used", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_seconds", sa.Integer(), nullable=True),
        sa.Column("excluded_seconds", sa.Integer(), nullable=False),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("submit_count", sa.Integer(), nullable=False),
        sa.Column(
            "submission_outcome",
            sa.Enum(
                "accepted",
                "wrong_answer",
                "runtime_error",
                "compile_error",
                "tle",
                "unknown",
                name="submission_outcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_resolve", sa.Boolean(), nullable=False),
        sa.Column("timed", sa.Boolean(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("extension", "manual", "public_sync", name="attempt_source", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "capture_confidence",
            sa.Enum("high", "medium", "low", name="capture_confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column("amended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prior_values", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("raw_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "active_seconds IS NULL OR active_seconds >= 0", name="ck_attempt_active"
        ),
        sa.CheckConstraint(
            "confidence_cold_redo IS NULL OR confidence_cold_redo BETWEEN 1 AND 5",
            name="ck_attempt_confidence_range",
        ),
        sa.CheckConstraint("excluded_seconds >= 0", name="ck_attempt_excluded"),
        sa.CheckConstraint(
            "hint_level_used IS NULL OR hint_level_used BETWEEN 1 AND 5",
            name="ck_attempt_hint_level_range",
        ),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attempts_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_attempts_user_submitted", ["user_id", "submitted_at"], unique=False
        )

    op.create_table(
        "plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "provisional",
                "active",
                "superseded",
                "rolled_back",
                name="plan_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("generation_context", sa.JSON(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["user_goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "version", name="uq_plan_user_version"),
    )
    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plans_user_id"), ["user_id"], unique=False)

    op.create_table(
        "problem_patterns",
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("pattern_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.CheckConstraint("weight > 0 AND weight <= 1", name="ck_problem_pattern_weight"),
        sa.ForeignKeyConstraint(["pattern_id"], ["patterns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("problem_id", "pattern_id"),
    )
    op.create_table(
        "attempt_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_uuid", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending",
                "processed",
                "duplicate",
                "invalid",
                name="processing_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attempt_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attempt_events_event_uuid"), ["event_uuid"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_attempt_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "plan_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=True),
        sa.Column(
            "item_type",
            sa.Enum(
                "practice", "resolve", "assessment", "learn", name="item_type", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("weakness", "interleaved", "retention", name="item_role", native_enum=False),
            nullable=False,
        ),
        sa.Column("target_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "done", "skipped", name="item_status", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "sequence", name="uq_plan_item_sequence"),
    )
    with op.batch_alter_table("plan_items", schema=None) as batch_op:
        batch_op.create_index("ix_plan_items_block", ["block_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_plan_items_plan_id"), ["plan_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plan_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_items_plan_id"))
        batch_op.drop_index("ix_plan_items_block")

    op.drop_table("plan_items")
    with op.batch_alter_table("attempt_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempt_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_events_event_uuid"))

    op.drop_table("attempt_events")
    op.drop_table("problem_patterns")
    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plans_user_id"))

    op.drop_table("plans")
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_attempts_user_submitted")
        batch_op.drop_index(batch_op.f("ix_attempts_user_id"))

    op.drop_table("attempts")
    with op.batch_alter_table("user_goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_goals_user_id"))

    op.drop_table("user_goals")
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.drop_index("ix_problems_active_rating")

    op.drop_table("problems")
    op.drop_table("pattern_prerequisites")
    op.drop_table("users")
    op.drop_table("patterns")
    op.drop_table("catalogue_sources")
    # ### end Alembic commands ###
