"""run snapshots and attempt conclusions

Revision ID: 897b04371238
Revises: e714a07710f1
Create Date: 2026-09-10 17:39:14.348204
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types render as `dsa_coach.db.X`; autogenerate does not add
# this import itself, and without it the migration fails at import time.
import dsa_coach.db


revision: str = "897b04371238"
down_revision: str | None = "e714a07710f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attempt_conclusions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("solved", "abandoned", name="episode_outcome", native_enum=False),
            nullable=False,
        ),
        sa.Column("patterns_used", sa.JSON(), nullable=False),
        sa.Column(
            "blocker_observed",
            sa.Enum(
                "pattern_not_recognized",
                "pattern_known_impl_failed",
                "edge_cases",
                "complexity",
                "data_structure_choice",
                "language_api",
                "misread_problem",
                name="blocker",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("final_complexity", sa.String(length=32), nullable=True),
        sa.Column("runs_before_pass", sa.Integer(), nullable=False),
        sa.Column("approach_changed", sa.Boolean(), nullable=False),
        sa.Column("converged_at_run", sa.Integer(), nullable=True),
        sa.Column("defects", sa.JSON(), nullable=False),
        sa.Column("vocabulary_version", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("runtime", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attempt_conclusions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attempt_conclusions_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_conclusions_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_conclusions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "attempt_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_uuid", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("run", "submit", name="snapshot_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("captured_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("conclusion_id", sa.Uuid(), nullable=True),
        sa.Column("retention_until", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conclusion_id"], ["attempt_conclusions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("attempt_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attempt_snapshots_captured_at"), ["captured_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_snapshots_conclusion_id"), ["conclusion_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_snapshots_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_snapshots_retention_until"), ["retention_until"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_snapshots_snapshot_uuid"), ["snapshot_uuid"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_attempt_snapshots_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_snapshot_open_episode", ["user_id", "problem_id", "conclusion_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attempt_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_snapshot_open_episode")
        batch_op.drop_index(batch_op.f("ix_attempt_snapshots_user_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_snapshots_snapshot_uuid"))
        batch_op.drop_index(batch_op.f("ix_attempt_snapshots_retention_until"))
        batch_op.drop_index(batch_op.f("ix_attempt_snapshots_problem_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_snapshots_conclusion_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_snapshots_captured_at"))

    op.drop_table("attempt_snapshots")
    with op.batch_alter_table("attempt_conclusions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempt_conclusions_user_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_conclusions_problem_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_conclusions_attempt_id"))

    op.drop_table("attempt_conclusions")
    # ### end Alembic commands ###
