"""phase 4 judgment layer

Revision ID: ad9da7c2d3c9
Revises: 0ebe455a34f6
Create Date: 2026-09-07 02:49:11.113675
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types render as `dsa_coach.db.X`; autogenerate does not add
# this import itself, and without it the migration fails at import time.
import dsa_coach.db


revision: str = "ad9da7c2d3c9"
down_revision: str | None = "0ebe455a34f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("agent_name", sa.String(length=80), nullable=False),
        sa.Column("trigger", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "succeeded", "failed", "unavailable", name="agent_run_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("runtime", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("input_summary", sa.Text(), nullable=False),
        sa.Column("output_summary", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.String(length=120), nullable=True),
        sa.Column("usage_metadata", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("started_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "plan_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=False),
        sa.Column("after_state", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("trigger", sa.String(length=80), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("reverted_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("plan_changes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_changes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "prescriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("focus_patterns", sa.JSON(), nullable=False),
        sa.Column("rating_band_low", sa.Integer(), nullable=False),
        sa.Column("rating_band_high", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mix", sa.JSON(), nullable=False),
        sa.Column("timed", sa.Boolean(), nullable=False),
        sa.Column("diagnosis", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("evidence_attempt_ids", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prescriptions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "prescription_validations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prescription_id", sa.Uuid(), nullable=False),
        sa.Column(
            "result",
            sa.Enum("accepted", "clamped", "rejected", name="validation_result", native_enum=False),
            nullable=False,
        ),
        sa.Column("violations", sa.JSON(), nullable=False),
        sa.Column("applied_plan_version", sa.Integer(), nullable=True),
        sa.Column("created_at", dsa_coach.db.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["prescription_id"], ["prescriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prescription_validations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prescription_validations_prescription_id"),
            ["prescription_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prescription_validations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prescription_validations_prescription_id"))

    op.drop_table("prescription_validations")
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prescriptions_user_id"))

    op.drop_table("prescriptions")
    with op.batch_alter_table("plan_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_changes_user_id"))

    op.drop_table("plan_changes")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_user_id"))

    op.drop_table("agent_runs")
    # ### end Alembic commands ###
